[package]
name = "nightrainsrbx/datastream"
version = "0.2.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
repository = "https://github.com/NightrainsRbx/DataStream"
license = "MIT"
authors = ["Nightrains"]
exclude = ["sourcemap.json", "dev.project.json", "test", ".luaurc"]

[dependencies]
Signal = "sleitnick/signal@2.0.1"
DeltaCompress = "nezuo/delta-compress@0.1.3"